//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDetailsServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkDetailsServiceReference.GetWorkDetailsSoap")]
    public interface GetWorkDetailsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkDetailsSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchResponse> WorkDetailsSearchAsync(WorkDetailsServiceReference.WorkDetailsSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkDetailsSearchExtended", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchExtendedResponse> WorkDetailsSearchExtendedAsync(WorkDetailsServiceReference.WorkDetailsSearchExtendedRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationToken
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceIPExtendedBO
    {
        
        private string cAEField;
        
        private string nameField;
        
        private string performingRightAffiliationField;
        
        private string roleTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CAE
        {
            get
            {
                return this.cAEField;
            }
            set
            {
                this.cAEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PerformingRightAffiliation
        {
            get
            {
                return this.performingRightAffiliationField;
            }
            set
            {
                this.performingRightAffiliationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RoleType
        {
            get
            {
                return this.roleTypeField;
            }
            set
            {
                this.roleTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkShareSummaryBO
    {
        
        private string categoryField;
        
        private decimal mechanicalSharePercentageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal MechanicalSharePercentage
        {
            get
            {
                return this.mechanicalSharePercentageField;
            }
            set
            {
                this.mechanicalSharePercentageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceWorkDetailsExtendedBO
    {
        
        private string[] iswcArrayField;
        
        private string[] libraryCatNumbersField;
        
        private WorkShareSummaryBO[] mechanicalShareSummaryField;
        
        private string priorApprovalCodeField;
        
        private string[] titleArrayField;
        
        private string tunecodeField;
        
        private string workStatusField;
        
        private string workTypeField;
        
        private WebServiceArtistBO[] artistArrayField;
        
        private WebServiceOwnerBO[] ownersMechArrayField;
        
        private WebServiceOwnerBO[] ownersPerfArrayField;
        
        private WebServiceIPExtendedBO[] publisherArrayField;
        
        private WebServiceIPExtendedBO[] writerArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] IswcArray
        {
            get
            {
                return this.iswcArrayField;
            }
            set
            {
                this.iswcArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] LibraryCatNumbers
        {
            get
            {
                return this.libraryCatNumbersField;
            }
            set
            {
                this.libraryCatNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public WorkShareSummaryBO[] MechanicalShareSummary
        {
            get
            {
                return this.mechanicalShareSummaryField;
            }
            set
            {
                this.mechanicalShareSummaryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PriorApprovalCode
        {
            get
            {
                return this.priorApprovalCodeField;
            }
            set
            {
                this.priorApprovalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public string[] TitleArray
        {
            get
            {
                return this.titleArrayField;
            }
            set
            {
                this.titleArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Tunecode
        {
            get
            {
                return this.tunecodeField;
            }
            set
            {
                this.tunecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string WorkStatus
        {
            get
            {
                return this.workStatusField;
            }
            set
            {
                this.workStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string WorkType
        {
            get
            {
                return this.workTypeField;
            }
            set
            {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public WebServiceArtistBO[] ArtistArray
        {
            get
            {
                return this.artistArrayField;
            }
            set
            {
                this.artistArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public WebServiceOwnerBO[] OwnersMechArray
        {
            get
            {
                return this.ownersMechArrayField;
            }
            set
            {
                this.ownersMechArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public WebServiceOwnerBO[] OwnersPerfArray
        {
            get
            {
                return this.ownersPerfArrayField;
            }
            set
            {
                this.ownersPerfArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public WebServiceIPExtendedBO[] PublisherArray
        {
            get
            {
                return this.publisherArrayField;
            }
            set
            {
                this.publisherArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public WebServiceIPExtendedBO[] WriterArray
        {
            get
            {
                return this.writerArrayField;
            }
            set
            {
                this.writerArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceArtistBO
    {
        
        private string nameField;
        
        private string artistIdField;
        
        private int numberRecordingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ArtistId
        {
            get
            {
                return this.artistIdField;
            }
            set
            {
                this.artistIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumberRecordings
        {
            get
            {
                return this.numberRecordingsField;
            }
            set
            {
                this.numberRecordingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceOwnerBO
    {
        
        private bool isPRSField;
        
        private string nameField;
        
        private string cAEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool IsPRS
        {
            get
            {
                return this.isPRSField;
            }
            set
            {
                this.isPRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CAE
        {
            get
            {
                return this.cAEField;
            }
            set
            {
                this.cAEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceIPBO
    {
        
        private string nameField;
        
        private string cAEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CAE
        {
            get
            {
                return this.cAEField;
            }
            set
            {
                this.cAEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceWorkDetailsBO
    {
        
        private string[] titleArrayField;
        
        private string tunecodeField;
        
        private string[] iswcArrayField;
        
        private string[] libraryCatNumbersField;
        
        private string workTypeField;
        
        private WebServiceOwnerBO[] ownersMechArrayField;
        
        private WebServiceOwnerBO[] ownersPerfArrayField;
        
        private WebServiceIPBO[] publisherArrayField;
        
        private WebServiceIPBO[] writerArrayField;
        
        private WebServiceArtistBO[] artistArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] TitleArray
        {
            get
            {
                return this.titleArrayField;
            }
            set
            {
                this.titleArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Tunecode
        {
            get
            {
                return this.tunecodeField;
            }
            set
            {
                this.tunecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public string[] IswcArray
        {
            get
            {
                return this.iswcArrayField;
            }
            set
            {
                this.iswcArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public string[] LibraryCatNumbers
        {
            get
            {
                return this.libraryCatNumbersField;
            }
            set
            {
                this.libraryCatNumbersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string WorkType
        {
            get
            {
                return this.workTypeField;
            }
            set
            {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public WebServiceOwnerBO[] OwnersMechArray
        {
            get
            {
                return this.ownersMechArrayField;
            }
            set
            {
                this.ownersMechArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public WebServiceOwnerBO[] OwnersPerfArray
        {
            get
            {
                return this.ownersPerfArrayField;
            }
            set
            {
                this.ownersPerfArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public WebServiceIPBO[] PublisherArray
        {
            get
            {
                return this.publisherArrayField;
            }
            set
            {
                this.publisherArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public WebServiceIPBO[] WriterArray
        {
            get
            {
                return this.writerArrayField;
            }
            set
            {
                this.writerArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public WebServiceArtistBO[] ArtistArray
        {
            get
            {
                return this.artistArrayField;
            }
            set
            {
                this.artistArrayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkDetailsSearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WorkDetailsSearchRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WorkDetailsServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Tunecode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string IncludeArtists;
        
        public WorkDetailsSearchRequest()
        {
        }
        
        public WorkDetailsSearchRequest(WorkDetailsServiceReference.AuthenticationToken AuthenticationToken, string Tunecode, string IncludeArtists)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.Tunecode = Tunecode;
            this.IncludeArtists = IncludeArtists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkDetailsSearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WorkDetailsSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorkDetailsServiceReference.WebServiceWorkDetailsBO WorkDetailsSearchResult;
        
        public WorkDetailsSearchResponse()
        {
        }
        
        public WorkDetailsSearchResponse(WorkDetailsServiceReference.WebServiceWorkDetailsBO WorkDetailsSearchResult)
        {
            this.WorkDetailsSearchResult = WorkDetailsSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkDetailsSearchExtended", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WorkDetailsSearchExtendedRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WorkDetailsServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Tunecode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string IncludeArtists;
        
        public WorkDetailsSearchExtendedRequest()
        {
        }
        
        public WorkDetailsSearchExtendedRequest(WorkDetailsServiceReference.AuthenticationToken AuthenticationToken, string Tunecode, string IncludeArtists)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.Tunecode = Tunecode;
            this.IncludeArtists = IncludeArtists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WorkDetailsSearchExtendedResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class WorkDetailsSearchExtendedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorkDetailsServiceReference.WebServiceWorkDetailsExtendedBO WorkDetailsSearchExtendedResult;
        
        public WorkDetailsSearchExtendedResponse()
        {
        }
        
        public WorkDetailsSearchExtendedResponse(WorkDetailsServiceReference.WebServiceWorkDetailsExtendedBO WorkDetailsSearchExtendedResult)
        {
            this.WorkDetailsSearchExtendedResult = WorkDetailsSearchExtendedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetWorkDetailsSoapChannel : WorkDetailsServiceReference.GetWorkDetailsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetWorkDetailsSoapClient : System.ServiceModel.ClientBase<WorkDetailsServiceReference.GetWorkDetailsSoap>, WorkDetailsServiceReference.GetWorkDetailsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetWorkDetailsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GetWorkDetailsSoapClient.GetBindingForEndpoint(endpointConfiguration), GetWorkDetailsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorkDetailsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetWorkDetailsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorkDetailsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetWorkDetailsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorkDetailsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchResponse> WorkDetailsServiceReference.GetWorkDetailsSoap.WorkDetailsSearchAsync(WorkDetailsServiceReference.WorkDetailsSearchRequest request)
        {
            return base.Channel.WorkDetailsSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchResponse> WorkDetailsSearchAsync(WorkDetailsServiceReference.AuthenticationToken AuthenticationToken, string Tunecode, string IncludeArtists)
        {
            WorkDetailsServiceReference.WorkDetailsSearchRequest inValue = new WorkDetailsServiceReference.WorkDetailsSearchRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.Tunecode = Tunecode;
            inValue.IncludeArtists = IncludeArtists;
            return ((WorkDetailsServiceReference.GetWorkDetailsSoap)(this)).WorkDetailsSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchExtendedResponse> WorkDetailsServiceReference.GetWorkDetailsSoap.WorkDetailsSearchExtendedAsync(WorkDetailsServiceReference.WorkDetailsSearchExtendedRequest request)
        {
            return base.Channel.WorkDetailsSearchExtendedAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorkDetailsServiceReference.WorkDetailsSearchExtendedResponse> WorkDetailsSearchExtendedAsync(WorkDetailsServiceReference.AuthenticationToken AuthenticationToken, string Tunecode, string IncludeArtists)
        {
            WorkDetailsServiceReference.WorkDetailsSearchExtendedRequest inValue = new WorkDetailsServiceReference.WorkDetailsSearchExtendedRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.Tunecode = Tunecode;
            inValue.IncludeArtists = IncludeArtists;
            return ((WorkDetailsServiceReference.GetWorkDetailsSoap)(this)).WorkDetailsSearchExtendedAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetWorkDetailsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GetWorkDetailsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetWorkDetailsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getworkdetails.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GetWorkDetailsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getworkdetails.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GetWorkDetailsSoap,
            
            GetWorkDetailsSoap12,
        }
    }
}
