//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordingServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecordingServiceReference.GetRecordingsSoap")]
    public interface GetRecordingsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewRecordingsSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecordingServiceReference.NewRecordingsSearchResponse> NewRecordingsSearchAsync(RecordingServiceReference.NewRecordingsSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCachedPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<RecordingServiceReference.GetCachedPageResponse> GetCachedPageAsync(RecordingServiceReference.GetCachedPageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationToken
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceRecordingsSummaryBO
    {
        
        private string title1Field;
        
        private string title2Field;
        
        private string artist1Field;
        
        private string artist2Field;
        
        private string originField;
        
        private string writersField;
        
        private string tuneCodeField;
        
        private string yearRecordedField;
        
        private string productionYearField;
        
        private string durationField;
        
        private string isrcNumberField;
        
        private string iswcNumberField;
        
        private int numberRecordingsField;
        
        private string productTrackPosField;
        
        private string productCatNoField;
        
        private string productLabelField;
        
        private string productTitleField;
        
        private string productIdField;
        
        private string workTypeField;
        
        private string workPublishersField;
        
        private string workArrangerField;
        
        private string workWriterField;
        
        private string workTitleField;
        
        private string recordingIdField;
        
        private string medleyTitleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title1
        {
            get
            {
                return this.title1Field;
            }
            set
            {
                this.title1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title2
        {
            get
            {
                return this.title2Field;
            }
            set
            {
                this.title2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Artist1
        {
            get
            {
                return this.artist1Field;
            }
            set
            {
                this.artist1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Artist2
        {
            get
            {
                return this.artist2Field;
            }
            set
            {
                this.artist2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Origin
        {
            get
            {
                return this.originField;
            }
            set
            {
                this.originField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Writers
        {
            get
            {
                return this.writersField;
            }
            set
            {
                this.writersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TuneCode
        {
            get
            {
                return this.tuneCodeField;
            }
            set
            {
                this.tuneCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string YearRecorded
        {
            get
            {
                return this.yearRecordedField;
            }
            set
            {
                this.yearRecordedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ProductionYear
        {
            get
            {
                return this.productionYearField;
            }
            set
            {
                this.productionYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Duration
        {
            get
            {
                return this.durationField;
            }
            set
            {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string IsrcNumber
        {
            get
            {
                return this.isrcNumberField;
            }
            set
            {
                this.isrcNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string IswcNumber
        {
            get
            {
                return this.iswcNumberField;
            }
            set
            {
                this.iswcNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int NumberRecordings
        {
            get
            {
                return this.numberRecordingsField;
            }
            set
            {
                this.numberRecordingsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ProductTrackPos
        {
            get
            {
                return this.productTrackPosField;
            }
            set
            {
                this.productTrackPosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ProductCatNo
        {
            get
            {
                return this.productCatNoField;
            }
            set
            {
                this.productCatNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ProductLabel
        {
            get
            {
                return this.productLabelField;
            }
            set
            {
                this.productLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string ProductTitle
        {
            get
            {
                return this.productTitleField;
            }
            set
            {
                this.productTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ProductId
        {
            get
            {
                return this.productIdField;
            }
            set
            {
                this.productIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string WorkType
        {
            get
            {
                return this.workTypeField;
            }
            set
            {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string WorkPublishers
        {
            get
            {
                return this.workPublishersField;
            }
            set
            {
                this.workPublishersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string WorkArranger
        {
            get
            {
                return this.workArrangerField;
            }
            set
            {
                this.workArrangerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string WorkWriter
        {
            get
            {
                return this.workWriterField;
            }
            set
            {
                this.workWriterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string WorkTitle
        {
            get
            {
                return this.workTitleField;
            }
            set
            {
                this.workTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string RecordingId
        {
            get
            {
                return this.recordingIdField;
            }
            set
            {
                this.recordingIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string MedleyTitle
        {
            get
            {
                return this.medleyTitleField;
            }
            set
            {
                this.medleyTitleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageBO
    {
        
        private string callNameField;
        
        private string callDurationField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        private string errorSeverityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CallName
        {
            get
            {
                return this.callNameField;
            }
            set
            {
                this.callNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CallDuration
        {
            get
            {
                return this.callDurationField;
            }
            set
            {
                this.callDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorSeverity
        {
            get
            {
                return this.errorSeverityField;
            }
            set
            {
                this.errorSeverityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceRecordingsSummariesBO
    {
        
        private int totalRecdgsFoundField;
        
        private string searchIdField;
        
        private MessageBO[] messagesField;
        
        private WebServiceRecordingsSummaryBO[] recordingSummaryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalRecdgsFound
        {
            get
            {
                return this.totalRecdgsFoundField;
            }
            set
            {
                this.totalRecdgsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchId
        {
            get
            {
                return this.searchIdField;
            }
            set
            {
                this.searchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public MessageBO[] Messages
        {
            get
            {
                return this.messagesField;
            }
            set
            {
                this.messagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public WebServiceRecordingsSummaryBO[] RecordingSummaryList
        {
            get
            {
                return this.recordingSummaryListField;
            }
            set
            {
                this.recordingSummaryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum RecordingInterestedPartyType
    {
        
        /// <remarks/>
        Recording_Title,
        
        /// <remarks/>
        Artist_Name,
        
        /// <remarks/>
        Product_Title,
        
        /// <remarks/>
        Title_Artist_Name,
        
        /// <remarks/>
        Title_Artist_Name_Product_Title,
        
        /// <remarks/>
        Artist_Name_Product_Title,
        
        /// <remarks/>
        Product_Title_Product_Label,
        
        /// <remarks/>
        ISRC_No,
        
        /// <remarks/>
        Product_CatNo,
        
        /// <remarks/>
        Product_CatNo_Track_Position,
        
        /// <remarks/>
        Tunecode,
        
        /// <remarks/>
        Tunecode_IPA_ID,
        
        /// <remarks/>
        Product_ID,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewRecordingsSearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewRecordingsSearchRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RecordingServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string ArtistName1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ArtistName2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string ProdTitle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string ProdLabel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string IsrcNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string ProdCatNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string TrackPos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string Tunecode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string IpaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string ProdID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string IncludeWorkDtls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string IncludeProdDtls;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string FuzzySearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string FirstRecordingOnly;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public RecordingServiceReference.RecordingInterestedPartyType ipType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public int pageSize;
        
        public NewRecordingsSearchRequest()
        {
        }
        
        public NewRecordingsSearchRequest(
                    RecordingServiceReference.AuthenticationToken AuthenticationToken, 
                    string Title, 
                    string ArtistName1, 
                    string ArtistName2, 
                    string ProdTitle, 
                    string ProdLabel, 
                    string IsrcNo, 
                    string ProdCatNo, 
                    string TrackPos, 
                    string Tunecode, 
                    string IpaId, 
                    string ProdID, 
                    string IncludeWorkDtls, 
                    string IncludeProdDtls, 
                    string FuzzySearch, 
                    string FirstRecordingOnly, 
                    RecordingServiceReference.RecordingInterestedPartyType ipType, 
                    int startRecord, 
                    int pageSize)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.Title = Title;
            this.ArtistName1 = ArtistName1;
            this.ArtistName2 = ArtistName2;
            this.ProdTitle = ProdTitle;
            this.ProdLabel = ProdLabel;
            this.IsrcNo = IsrcNo;
            this.ProdCatNo = ProdCatNo;
            this.TrackPos = TrackPos;
            this.Tunecode = Tunecode;
            this.IpaId = IpaId;
            this.ProdID = ProdID;
            this.IncludeWorkDtls = IncludeWorkDtls;
            this.IncludeProdDtls = IncludeProdDtls;
            this.FuzzySearch = FuzzySearch;
            this.FirstRecordingOnly = FirstRecordingOnly;
            this.ipType = ipType;
            this.startRecord = startRecord;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewRecordingsSearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewRecordingsSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RecordingServiceReference.WebServiceRecordingsSummariesBO NewRecordingsSearchResult;
        
        public NewRecordingsSearchResponse()
        {
        }
        
        public NewRecordingsSearchResponse(RecordingServiceReference.WebServiceRecordingsSummariesBO NewRecordingsSearchResult)
        {
            this.NewRecordingsSearchResult = NewRecordingsSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCachedPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCachedPageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public RecordingServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string searchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int pageSize;
        
        public GetCachedPageRequest()
        {
        }
        
        public GetCachedPageRequest(RecordingServiceReference.AuthenticationToken AuthenticationToken, string searchId, int startRecord, int pageSize)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.searchId = searchId;
            this.startRecord = startRecord;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCachedPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCachedPageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public RecordingServiceReference.WebServiceRecordingsSummariesBO GetCachedPageResult;
        
        public GetCachedPageResponse()
        {
        }
        
        public GetCachedPageResponse(RecordingServiceReference.WebServiceRecordingsSummariesBO GetCachedPageResult)
        {
            this.GetCachedPageResult = GetCachedPageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetRecordingsSoapChannel : RecordingServiceReference.GetRecordingsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetRecordingsSoapClient : System.ServiceModel.ClientBase<RecordingServiceReference.GetRecordingsSoap>, RecordingServiceReference.GetRecordingsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetRecordingsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GetRecordingsSoapClient.GetBindingForEndpoint(endpointConfiguration), GetRecordingsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetRecordingsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetRecordingsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetRecordingsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetRecordingsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetRecordingsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecordingServiceReference.NewRecordingsSearchResponse> RecordingServiceReference.GetRecordingsSoap.NewRecordingsSearchAsync(RecordingServiceReference.NewRecordingsSearchRequest request)
        {
            return base.Channel.NewRecordingsSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecordingServiceReference.NewRecordingsSearchResponse> NewRecordingsSearchAsync(
                    RecordingServiceReference.AuthenticationToken AuthenticationToken, 
                    string Title, 
                    string ArtistName1, 
                    string ArtistName2, 
                    string ProdTitle, 
                    string ProdLabel, 
                    string IsrcNo, 
                    string ProdCatNo, 
                    string TrackPos, 
                    string Tunecode, 
                    string IpaId, 
                    string ProdID, 
                    string IncludeWorkDtls, 
                    string IncludeProdDtls, 
                    string FuzzySearch, 
                    string FirstRecordingOnly, 
                    RecordingServiceReference.RecordingInterestedPartyType ipType, 
                    int startRecord, 
                    int pageSize)
        {
            RecordingServiceReference.NewRecordingsSearchRequest inValue = new RecordingServiceReference.NewRecordingsSearchRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.Title = Title;
            inValue.ArtistName1 = ArtistName1;
            inValue.ArtistName2 = ArtistName2;
            inValue.ProdTitle = ProdTitle;
            inValue.ProdLabel = ProdLabel;
            inValue.IsrcNo = IsrcNo;
            inValue.ProdCatNo = ProdCatNo;
            inValue.TrackPos = TrackPos;
            inValue.Tunecode = Tunecode;
            inValue.IpaId = IpaId;
            inValue.ProdID = ProdID;
            inValue.IncludeWorkDtls = IncludeWorkDtls;
            inValue.IncludeProdDtls = IncludeProdDtls;
            inValue.FuzzySearch = FuzzySearch;
            inValue.FirstRecordingOnly = FirstRecordingOnly;
            inValue.ipType = ipType;
            inValue.startRecord = startRecord;
            inValue.pageSize = pageSize;
            return ((RecordingServiceReference.GetRecordingsSoap)(this)).NewRecordingsSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RecordingServiceReference.GetCachedPageResponse> RecordingServiceReference.GetRecordingsSoap.GetCachedPageAsync(RecordingServiceReference.GetCachedPageRequest request)
        {
            return base.Channel.GetCachedPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<RecordingServiceReference.GetCachedPageResponse> GetCachedPageAsync(RecordingServiceReference.AuthenticationToken AuthenticationToken, string searchId, int startRecord, int pageSize)
        {
            RecordingServiceReference.GetCachedPageRequest inValue = new RecordingServiceReference.GetCachedPageRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.searchId = searchId;
            inValue.startRecord = startRecord;
            inValue.pageSize = pageSize;
            return ((RecordingServiceReference.GetRecordingsSoap)(this)).GetCachedPageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetRecordingsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GetRecordingsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetRecordingsSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getrecordings.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GetRecordingsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getrecordings.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GetRecordingsSoap,
            
            GetRecordingsSoap12,
        }
    }
}
