//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorksServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorksServiceReference.GetWorksSoap")]
    public interface GetWorksSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NewWorkSearch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WorksServiceReference.NewWorkSearchResponse> NewWorkSearchAsync(WorksServiceReference.NewWorkSearchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCachedPage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<WorksServiceReference.GetCachedPageResponse> GetCachedPageAsync(WorksServiceReference.GetCachedPageRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticationToken
    {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SessionId
        {
            get
            {
                return this.sessionIdField;
            }
            set
            {
                this.sessionIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceArtistBO
    {
        
        private string nameField;
        
        private string artistIdField;
        
        private int numberRecordingsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ArtistId
        {
            get
            {
                return this.artistIdField;
            }
            set
            {
                this.artistIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int NumberRecordings
        {
            get
            {
                return this.numberRecordingsField;
            }
            set
            {
                this.numberRecordingsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceWorkSummaryBO
    {
        
        private string titleField;
        
        private string tunecodeField;
        
        private string iswcArrayField;
        
        private string libraryCatNoField;
        
        private string workTypeField;
        
        private string[] publisherArrayField;
        
        private string[] writerArrayField;
        
        private WebServiceArtistBO[] artistArrayField;
        
        private int noOfArtistsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Tunecode
        {
            get
            {
                return this.tunecodeField;
            }
            set
            {
                this.tunecodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IswcArray
        {
            get
            {
                return this.iswcArrayField;
            }
            set
            {
                this.iswcArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LibraryCatNo
        {
            get
            {
                return this.libraryCatNoField;
            }
            set
            {
                this.libraryCatNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string WorkType
        {
            get
            {
                return this.workTypeField;
            }
            set
            {
                this.workTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] PublisherArray
        {
            get
            {
                return this.publisherArrayField;
            }
            set
            {
                this.publisherArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] WriterArray
        {
            get
            {
                return this.writerArrayField;
            }
            set
            {
                this.writerArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        public WebServiceArtistBO[] ArtistArray
        {
            get
            {
                return this.artistArrayField;
            }
            set
            {
                this.artistArrayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int NoOfArtists
        {
            get
            {
                return this.noOfArtistsField;
            }
            set
            {
                this.noOfArtistsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceWorkSummariesBO
    {
        
        private int totalRecdgsFoundField;
        
        private string searchIdField;
        
        private WebServiceWorkSummaryBO[] workSummaryListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalRecdgsFound
        {
            get
            {
                return this.totalRecdgsFoundField;
            }
            set
            {
                this.totalRecdgsFoundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SearchId
        {
            get
            {
                return this.searchIdField;
            }
            set
            {
                this.searchIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public WebServiceWorkSummaryBO[] WorkSummaryList
        {
            get
            {
                return this.workSummaryListField;
            }
            set
            {
                this.workSummaryListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum InterestedPartyType
    {
        
        /// <remarks/>
        Work_Title,
        
        /// <remarks/>
        Work_Writer_Name,
        
        /// <remarks/>
        Work_Writer_CAE,
        
        /// <remarks/>
        Work_Title_Writer_Name,
        
        /// <remarks/>
        Work_Title_Writer_CAE,
        
        /// <remarks/>
        Work_Title_Publ_Name,
        
        /// <remarks/>
        Work_Title_Publ_CAE,
        
        /// <remarks/>
        Work_Title_Writer_Name_Publ_Name,
        
        /// <remarks/>
        Work_Title_Writer_CAE_Publ_CAE,
        
        /// <remarks/>
        Tunecode,
        
        /// <remarks/>
        ISWC_No,
        
        /// <remarks/>
        Lib_Cat_No,
        
        /// <remarks/>
        Lib_Cat_No_Track_Position,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewWorkSearch", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewWorkSearchRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WorksServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string WriterName1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string WriterName2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string WriterName3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string WriterName4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string WriterName5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string WriterCAE1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string WriterCAE2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string WriterCAE3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public string WriterCAE4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public string WriterCAE5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public string PublisherName1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public string PublisherName2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=13)]
        public string PublisherName3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=14)]
        public string PublisherName4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=15)]
        public string PublisherName5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=16)]
        public string PublisherCAE1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=17)]
        public string PublisherCAE2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=18)]
        public string PublisherCAE3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=19)]
        public string PublisherCAE4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=20)]
        public string PublisherCAE5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=21)]
        public string Tunecode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=22)]
        public string ISWC;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=23)]
        public string LibCatNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=24)]
        public string TrackPos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=25)]
        public string FuzzySearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=26)]
        public string IncludeArtists;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=27)]
        public WorksServiceReference.InterestedPartyType ipType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=28)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=29)]
        public int pageSize;
        
        public NewWorkSearchRequest()
        {
        }
        
        public NewWorkSearchRequest(
                    WorksServiceReference.AuthenticationToken AuthenticationToken, 
                    string title, 
                    string WriterName1, 
                    string WriterName2, 
                    string WriterName3, 
                    string WriterName4, 
                    string WriterName5, 
                    string WriterCAE1, 
                    string WriterCAE2, 
                    string WriterCAE3, 
                    string WriterCAE4, 
                    string WriterCAE5, 
                    string PublisherName1, 
                    string PublisherName2, 
                    string PublisherName3, 
                    string PublisherName4, 
                    string PublisherName5, 
                    string PublisherCAE1, 
                    string PublisherCAE2, 
                    string PublisherCAE3, 
                    string PublisherCAE4, 
                    string PublisherCAE5, 
                    string Tunecode, 
                    string ISWC, 
                    string LibCatNo, 
                    string TrackPos, 
                    string FuzzySearch, 
                    string IncludeArtists, 
                    WorksServiceReference.InterestedPartyType ipType, 
                    int startRecord, 
                    int pageSize)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.title = title;
            this.WriterName1 = WriterName1;
            this.WriterName2 = WriterName2;
            this.WriterName3 = WriterName3;
            this.WriterName4 = WriterName4;
            this.WriterName5 = WriterName5;
            this.WriterCAE1 = WriterCAE1;
            this.WriterCAE2 = WriterCAE2;
            this.WriterCAE3 = WriterCAE3;
            this.WriterCAE4 = WriterCAE4;
            this.WriterCAE5 = WriterCAE5;
            this.PublisherName1 = PublisherName1;
            this.PublisherName2 = PublisherName2;
            this.PublisherName3 = PublisherName3;
            this.PublisherName4 = PublisherName4;
            this.PublisherName5 = PublisherName5;
            this.PublisherCAE1 = PublisherCAE1;
            this.PublisherCAE2 = PublisherCAE2;
            this.PublisherCAE3 = PublisherCAE3;
            this.PublisherCAE4 = PublisherCAE4;
            this.PublisherCAE5 = PublisherCAE5;
            this.Tunecode = Tunecode;
            this.ISWC = ISWC;
            this.LibCatNo = LibCatNo;
            this.TrackPos = TrackPos;
            this.FuzzySearch = FuzzySearch;
            this.IncludeArtists = IncludeArtists;
            this.ipType = ipType;
            this.startRecord = startRecord;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewWorkSearchResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class NewWorkSearchResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorksServiceReference.WebServiceWorkSummariesBO NewWorkSearchResult;
        
        public NewWorkSearchResponse()
        {
        }
        
        public NewWorkSearchResponse(WorksServiceReference.WebServiceWorkSummariesBO NewWorkSearchResult)
        {
            this.NewWorkSearchResult = NewWorkSearchResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCachedPage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCachedPageRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public WorksServiceReference.AuthenticationToken AuthenticationToken;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string searchId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int startRecord;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int PageSize;
        
        public GetCachedPageRequest()
        {
        }
        
        public GetCachedPageRequest(WorksServiceReference.AuthenticationToken AuthenticationToken, string searchId, int startRecord, int PageSize)
        {
            this.AuthenticationToken = AuthenticationToken;
            this.searchId = searchId;
            this.startRecord = startRecord;
            this.PageSize = PageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCachedPageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCachedPageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public WorksServiceReference.WebServiceWorkSummariesBO GetCachedPageResult;
        
        public GetCachedPageResponse()
        {
        }
        
        public GetCachedPageResponse(WorksServiceReference.WebServiceWorkSummariesBO GetCachedPageResult)
        {
            this.GetCachedPageResult = GetCachedPageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface GetWorksSoapChannel : WorksServiceReference.GetWorksSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class GetWorksSoapClient : System.ServiceModel.ClientBase<WorksServiceReference.GetWorksSoap>, WorksServiceReference.GetWorksSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetWorksSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(GetWorksSoapClient.GetBindingForEndpoint(endpointConfiguration), GetWorksSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorksSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetWorksSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorksSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetWorksSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetWorksSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorksServiceReference.NewWorkSearchResponse> WorksServiceReference.GetWorksSoap.NewWorkSearchAsync(WorksServiceReference.NewWorkSearchRequest request)
        {
            return base.Channel.NewWorkSearchAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorksServiceReference.NewWorkSearchResponse> NewWorkSearchAsync(
                    WorksServiceReference.AuthenticationToken AuthenticationToken, 
                    string title, 
                    string WriterName1, 
                    string WriterName2, 
                    string WriterName3, 
                    string WriterName4, 
                    string WriterName5, 
                    string WriterCAE1, 
                    string WriterCAE2, 
                    string WriterCAE3, 
                    string WriterCAE4, 
                    string WriterCAE5, 
                    string PublisherName1, 
                    string PublisherName2, 
                    string PublisherName3, 
                    string PublisherName4, 
                    string PublisherName5, 
                    string PublisherCAE1, 
                    string PublisherCAE2, 
                    string PublisherCAE3, 
                    string PublisherCAE4, 
                    string PublisherCAE5, 
                    string Tunecode, 
                    string ISWC, 
                    string LibCatNo, 
                    string TrackPos, 
                    string FuzzySearch, 
                    string IncludeArtists, 
                    WorksServiceReference.InterestedPartyType ipType, 
                    int startRecord, 
                    int pageSize)
        {
            WorksServiceReference.NewWorkSearchRequest inValue = new WorksServiceReference.NewWorkSearchRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.title = title;
            inValue.WriterName1 = WriterName1;
            inValue.WriterName2 = WriterName2;
            inValue.WriterName3 = WriterName3;
            inValue.WriterName4 = WriterName4;
            inValue.WriterName5 = WriterName5;
            inValue.WriterCAE1 = WriterCAE1;
            inValue.WriterCAE2 = WriterCAE2;
            inValue.WriterCAE3 = WriterCAE3;
            inValue.WriterCAE4 = WriterCAE4;
            inValue.WriterCAE5 = WriterCAE5;
            inValue.PublisherName1 = PublisherName1;
            inValue.PublisherName2 = PublisherName2;
            inValue.PublisherName3 = PublisherName3;
            inValue.PublisherName4 = PublisherName4;
            inValue.PublisherName5 = PublisherName5;
            inValue.PublisherCAE1 = PublisherCAE1;
            inValue.PublisherCAE2 = PublisherCAE2;
            inValue.PublisherCAE3 = PublisherCAE3;
            inValue.PublisherCAE4 = PublisherCAE4;
            inValue.PublisherCAE5 = PublisherCAE5;
            inValue.Tunecode = Tunecode;
            inValue.ISWC = ISWC;
            inValue.LibCatNo = LibCatNo;
            inValue.TrackPos = TrackPos;
            inValue.FuzzySearch = FuzzySearch;
            inValue.IncludeArtists = IncludeArtists;
            inValue.ipType = ipType;
            inValue.startRecord = startRecord;
            inValue.pageSize = pageSize;
            return ((WorksServiceReference.GetWorksSoap)(this)).NewWorkSearchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WorksServiceReference.GetCachedPageResponse> WorksServiceReference.GetWorksSoap.GetCachedPageAsync(WorksServiceReference.GetCachedPageRequest request)
        {
            return base.Channel.GetCachedPageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WorksServiceReference.GetCachedPageResponse> GetCachedPageAsync(WorksServiceReference.AuthenticationToken AuthenticationToken, string searchId, int startRecord, int PageSize)
        {
            WorksServiceReference.GetCachedPageRequest inValue = new WorksServiceReference.GetCachedPageRequest();
            inValue.AuthenticationToken = AuthenticationToken;
            inValue.searchId = searchId;
            inValue.startRecord = startRecord;
            inValue.PageSize = PageSize;
            return ((WorksServiceReference.GetWorksSoap)(this)).GetCachedPageAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetWorksSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GetWorksSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetWorksSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getworks.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GetWorksSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://services.prsformusic.com/coredataws/getworks.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GetWorksSoap,
            
            GetWorksSoap12,
        }
    }
}
